version: '3.8'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
  backend:
    depends_on:
      - mongo
    build: ./backend
    restart: always
    ports:
      - '5001:5001'
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      - MONGO_DB_URI_DEV=mongodb://root:secret@mongo:27017/chat?authSource=admin
  frontend:
    depends_on:
      - backend
    build: ./frontend
    ports:
      - '5173:5173'
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - VITE_APP_BASE_URL=http://localhost:5001/api/v1